// Network requests
export const FETCH_COMPANIES_REQUEST = 'FETCH_COMPANIES_REQUEST'
export const FETCH_COMPANIES_SUCCESS = 'FETCH_COMPANIES_SUCCESS'
export const FETCH_COMPANIES_FAILURE = 'FETCH_COMPANIES_FAILURE'

// User interaction
export const TOGGLE_CHANGE_MAP = 'TOGGLE_CHANGE_MAP'
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE'
export const TOGGLE_SHOW_FAVORITES = 'TOGGLE_SHOW_FAVORITES'
export const SEARCH_COMPANY = 'SEARCH_COMPANY'
export const ADD_COMPANY_FILTER = 'ADD_COMPANY_FILTER'
export const CLEAR_COMPANY_FILTER = 'CLEAR_COMPANY_FILTER'
